services:
  - type: web
    name: heartsmart-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn frontend.src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
